name: Build Clicker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Fix JAVA_HOME manually
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH


      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Download Android NDK r25b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d $HOME
          echo "ANDROIDNDK=$HOME/android-ndk-r25b" >> $GITHUB_ENV

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: build
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: clicker-apk
          path: ${{ steps.build.outputs.filename }}
